name: Release

on:
    release:
        types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o fileb-${{ matrix.goos }}-${{ matrix.goarch }}
      
    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./fileb-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_name: fileb-${{ matrix.goos }}-${{ matrix.goarch }}
        asset_content_type: application/octet-stream