name: Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [amd64]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '^1.21'

    - name: Check out code
      uses: actions/checkout@v3

    - name: Build
      run: |
        env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -v -o fileb-${{ matrix.goos }}-${{ matrix.goarch }}
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: fileb-${{ matrix.goos }}-${{ matrix.goarch }}
        path: fileb-${{ matrix.goos }}-${{ matrix.goarch }}